### ISSUE TITLE
Delete listview item cause a problem

### ISSUE THREAD

**Issue by maanu** [dharanikumar/IOS_7-SwipeGesture-Android#4]
Hello,

I have made custom listview adapter.and trying to delete row.It is deleted when there is a one row in listview.but when there is more than one row it gives an error in deleting row.
Thanks

**Comment by dharanikumar** [comment]
I have made a fix.. check it now

**Comment by maanu** [comment]
Hello,
Thanks for reply.
But I face same problem with deletion.Works fine when its only one row of listview.When there comes more than one row its perform delete operation but throw an error after.

ERROR:

 Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
            at android.widget.AdapterView.getPositionForView(AdapterView.java:602)
            at com.swipe.ListViewSwipeGesture$touchClass.onTouch(ListViewSwipeGesture.java:562)

Thanks
